version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    volumes:
      - ./src/:/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT1:-80}:80
      - ${WEB_PORT2:-443}:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: